name: mobievent
description: "Alquiler mobiliario para eventos - MVP"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  provider: ^6.1.5+1
  intl: ^0.20.2
  http: ^1.6.0
  # note: removed google maps and geolocator - app uses numeric km picker
  uuid: ^4.5.2
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
